export const partnersData = [
    // Digital Lending Apps
    {
        id: 1,
        name: "InVision",
        category: "Fintech partners",
        logo: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=200&h=200&fit=crop&crop=center",
        description: "Modern digital lending platform providing quick personal and business loans with AI-powered risk assessment.",
        shortDescription: "AI-powered digital lending solutions for personal and business loans with instant approvals.",
        specialties: ["Personal Loans", "Business Loans", "Credit Assessment", "AI Risk Analysis"],
        loanRange: "₹50,000 - ₹50,00,000",
        processingTime: "24-48 hours",
        interestRate: "12% - 24% per annum",
        eligibility: "Credit score 650+, Income proof, Age 21-65",
        features: [
            "100% Digital Process",
            "AI-powered Credit Assessment",
            "Instant Approval",
            "Flexible Repayment Options",
            "24/7 Customer Support"
        ],
        contactEmail: "partnerships@invision.com",
        contactPhone: "+91-9876543210",
        established: "2018",
        totalDisbursed: "₹2,500 Crores",
        activeLoans: "1,25,000+",
        website: "https://invision.com"
    },
    {
        id: 2,
        name: "Zeplin Finance",
        category: "Fintech partners",
        logo: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=200&h=200&fit=crop&crop=center",
        description: "Innovative fintech platform specializing in SME lending and working capital solutions.",
        shortDescription: "SME focused lending platform with working capital and business expansion loans.",
        specialties: ["SME Loans", "Working Capital", "Invoice Financing", "Equipment Loans"],
        loanRange: "₹1,00,000 - ₹1,00,00,000",
        processingTime: "48-72 hours",
        interestRate: "14% - 28% per annum",
        eligibility: "GST registered, 2+ years in business, Annual turnover ₹25L+",
        features: [
            "Quick SME Approvals",
            "Working Capital Solutions",
            "Invoice Financing",
            "Equipment Financing",
            "Business Analytics Dashboard"
        ],
        contactEmail: "business@zeplin.com",
        contactPhone: "+91-9876543211",
        established: "2019",
        totalDisbursed: "₹1,800 Crores",
        activeLoans: "85,000+",
        website: "https://zeplin.com"
    },
    // {
    //     id: 3,
    //     name: "Asana Capital",
    //     category: "DIGITAL_LENDING_APPS",
    //     logo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=200&h=200&fit=crop&crop=center",
    //     description: "Digital-first lending platform focusing on education loans and personal development financing.",
    //     shortDescription: "Education and personal development loans with flexible repayment options.",
    //     specialties: ["Education Loans", "Skill Development", "Professional Courses", "Study Abroad"],
    //     loanRange: "₹25,000 - ₹25,00,000",
    //     processingTime: "24-36 hours",
    //     interestRate: "10% - 18% per annum",
    //     eligibility: "Admission confirmation, Co-applicant required, Age 18-35",
    //     features: [
    //         "Education Loan Specialist",
    //         "Moratorium Period Available",
    //         "Flexible EMI Options",
    //         "Digital Document Verification",
    //         "Study Abroad Support"
    //     ],
    //     contactEmail: "support@asana-capital.com",
    //     contactPhone: "+91-9876543212",
    //     established: "2020",
    //     totalDisbursed: "₹950 Crores",
    //     activeLoans: "45,000+",
    //     website: "https://asana-capital.com"
    // },
    // {
    //     id: 4,
    //     name: "Shopify Pay",
    //     category: "DIGITAL_LENDING_APPS",
    //     logo: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=200&h=200&fit=crop&crop=center",
    //     description: "E-commerce focused lending solutions for online merchants and sellers.",
    //     shortDescription: "E-commerce lending solutions for online merchants and marketplace sellers.",
    //     specialties: ["Merchant Loans", "Inventory Financing", "Revenue-based Loans", "Marketplace Lending"],
    //     loanRange: "₹50,000 - ₹75,00,000",
    //     processingTime: "12-24 hours",
    //     interestRate: "16% - 32% per annum",
    //     eligibility: "Active online store, 6+ months trading, Monthly revenue ₹1L+",
    //     features: [
    //         "Revenue-based Lending",
    //         "Inventory Financing",
    //         "Quick Merchant Approvals",
    //         "Integration with E-commerce Platforms",
    //         "Real-time Sales Analytics"
    //     ],
    //     contactEmail: "merchants@shopify-pay.com",
    //     contactPhone: "+91-9876543213",
    //     established: "2021",
    //     totalDisbursed: "₹750 Crores",
    //     activeLoans: "35,000+",
    //     website: "https://shopify-pay.com"
    // },

    // // Non-Digital Lending Apps
    // {
    //     id: 5,
    //     name: "PayPal Credit",
    //     category: "NON_DIGITAL_LENDING_APPS",
    //     logo: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=200&h=200&fit=crop&crop=center",
    //     description: "Traditional lending institution with branch-based services and personalized loan solutions.",
    //     shortDescription: "Traditional branch-based lending with personalized loan consultation services.",
    //     specialties: ["Home Loans", "Personal Loans", "Gold Loans", "Vehicle Loans"],
    //     loanRange: "₹1,00,000 - ₹5,00,00,000",
    //     processingTime: "7-14 days",
    //     interestRate: "8% - 20% per annum",
    //     eligibility: "Income proof, Property documents, Credit history, Age 21-70",
    //     features: [
    //         "Branch-based Service",
    //         "Personal Loan Consultation",
    //         "Comprehensive Documentation Support",
    //         "Relationship Banking",
    //         "Flexible Repayment Terms"
    //     ],
    //     contactEmail: "loans@paypal-credit.com",
    //     contactPhone: "+91-9876543214",
    //     established: "2010",
    //     totalDisbursed: "₹15,000 Crores",
    //     activeLoans: "2,50,000+",
    //     website: "https://paypal-credit.com"
    // },
    // {
    //     id: 6,
    //     name: "Slack Financial",
    //     category: "NON_DIGITAL_LENDING_APPS",
    //     logo: "https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=200&h=200&fit=crop&crop=center",
    //     description: "Regional financial institution specializing in agricultural and rural lending solutions.",
    //     shortDescription: "Agricultural and rural lending specialist with deep local market understanding.",
    //     specialties: ["Agriculture Loans", "Rural Development", "Micro Finance", "Cooperative Lending"],
    //     loanRange: "₹25,000 - ₹50,00,000",
    //     processingTime: "10-21 days",
    //     interestRate: "6% - 16% per annum",
    //     eligibility: "Land ownership, Agricultural income, Age 18-65, Rural residence",
    //     features: [
    //         "Agricultural Expertise",
    //         "Rural Area Coverage",
    //         "Subsidized Interest Rates",
    //         "Seasonal Repayment Options",
    //         "Local Language Support"
    //     ],
    //     contactEmail: "rural@slack-financial.com",
    //     contactPhone: "+91-9876543215",
    //     established: "2008",
    //     totalDisbursed: "₹8,500 Crores",
    //     activeLoans: "1,75,000+",
    //     website: "https://slack-financial.com"
    // },
    // {
    //     id: 7,
    //     name: "WordPress Capital",
    //     category: "NON_DIGITAL_LENDING_APPS",
    //     logo: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=200&h=200&fit=crop&crop=center",
    //     description: "Corporate lending specialist focusing on large-scale business financing and infrastructure projects.",
    //     shortDescription: "Corporate lending specialist for large-scale business and infrastructure financing.",
    //     specialties: ["Corporate Loans", "Infrastructure Financing", "Project Finance", "Term Loans"],
    //     loanRange: "₹1,00,00,000 - ₹100,00,00,000",
    //     processingTime: "30-60 days",
    //     interestRate: "7% - 15% per annum",
    //     eligibility: "Corporate entity, 5+ years operation, Audited financials, Promoter guarantee",
    //     features: [
    //         "Large Ticket Financing",
    //         "Infrastructure Project Support",
    //         "Corporate Advisory Services",
    //         "Structured Finance Solutions",
    //         "Long-term Partnerships"
    //     ],
    //     contactEmail: "corporate@wordpress-capital.com",
    //     contactPhone: "+91-9876543216",
    //     established: "2005",
    //     totalDisbursed: "₹45,000 Crores",
    //     activeLoans: "5,000+",
    //     website: "https://wordpress-capital.com"
    // },
    // {
    //     id: 8,
    //     name: "HubSpot Finance",
    //     category: "NON_DIGITAL_LENDING_APPS",
    //     logo: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=200&h=200&fit=crop&crop=center",
    //     description: "Community-focused lending institution with emphasis on social impact and inclusive finance.",
    //     shortDescription: "Community-focused lending with emphasis on social impact and inclusive finance.",
    //     specialties: ["Community Lending", "Social Impact Finance", "Women Entrepreneurs", "Inclusive Finance"],
    //     loanRange: "₹10,000 - ₹10,00,000",
    //     processingTime: "5-10 days",
    //     interestRate: "8% - 18% per annum",
    //     eligibility: "Community member, Social impact focus, Age 18-60, Basic income proof",
    //     features: [
    //         "Community-based Lending",
    //         "Social Impact Focus",
    //         "Women Entrepreneur Support",
    //         "Financial Literacy Programs",
    //         "Flexible Eligibility Criteria"
    //     ],
    //     contactEmail: "community@hubspot-finance.com",
    //     contactPhone: "+91-9876543217",
    //     established: "2012",
    //     totalDisbursed: "₹3,200 Crores",
    //     activeLoans: "1,50,000+",
    //     website: "https://hubspot-finance.com"
    // },

    // // Co-lending Partnerships
    // {
    //     id: 9,
    //     name: "Harvest Co-lending",
    //     category: "CO_LENDING_PARTNERSHIPS",
    //     logo: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=200&h=200&fit=crop&crop=center",
    //     description: "Strategic co-lending platform connecting multiple financial institutions for risk-sharing.",
    //     shortDescription: "Strategic co-lending platform for risk-sharing between multiple financial institutions.",
    //     specialties: ["Risk Sharing", "Co-lending Platform", "Multi-Institution Loans", "Syndicated Lending"],
    //     loanRange: "₹5,00,000 - ₹50,00,00,000",
    //     processingTime: "14-30 days",
    //     interestRate: "9% - 22% per annum",
    //     eligibility: "Varies by partner institution, Comprehensive evaluation required",
    //     features: [
    //         "Multi-Institution Partnership",
    //         "Risk Distribution",
    //         "Competitive Interest Rates",
    //         "Large Loan Capacity",
    //         "Comprehensive Risk Assessment"
    //     ],
    //     contactEmail: "partnerships@harvest-colending.com",
    //     contactPhone: "+91-9876543218",
    //     established: "2017",
    //     totalDisbursed: "₹12,000 Crores",
    //     activeLoans: "65,000+",
    //     website: "https://harvest-colending.com"
    // },
    // {
    //     id: 10,
    //     name: "Unity Financial Network",
    //     category: "CO_LENDING_PARTNERSHIPS",
    //     logo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=center",
    //     description: "Collaborative lending network facilitating partnerships between banks and NBFCs.",
    //     shortDescription: "Collaborative network facilitating partnerships between banks and NBFCs.",
    //     specialties: ["Bank-NBFC Partnerships", "Collaborative Lending", "Credit Enhancement", "Portfolio Sharing"],
    //     loanRange: "₹2,00,000 - ₹25,00,00,000",
    //     processingTime: "10-21 days",
    //     interestRate: "8% - 20% per annum",
    //     eligibility: "Multi-tier evaluation, Bank and NBFC approval required",
    //     features: [
    //         "Bank-NBFC Collaboration",
    //         "Credit Enhancement Services",
    //         "Portfolio Diversification",
    //         "Regulatory Compliance",
    //         "Technology Platform Integration"
    //     ],
    //     contactEmail: "network@unity-financial.com",
    //     contactPhone: "+91-9876543219",
    //     established: "2016",
    //     totalDisbursed: "₹18,500 Crores",
    //     activeLoans: "95,000+",
    //     website: "https://unity-financial.com"
    // },
    // {
    //     id: 11,
    //     name: "Synergy Lending Hub",
    //     category: "CO_LENDING_PARTNERSHIPS",
    //     logo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=200&h=200&fit=crop&crop=center",
    //     description: "Technology-enabled co-lending platform with AI-powered risk assessment and matching.",
    //     shortDescription: "Technology-enabled co-lending with AI-powered risk assessment and partner matching.",
    //     specialties: ["AI-powered Matching", "Tech-enabled Co-lending", "Risk Analytics", "Partner Optimization"],
    //     loanRange: "₹1,00,000 - ₹10,00,00,000",
    //     processingTime: "7-14 days",
    //     interestRate: "10% - 25% per annum",
    //     eligibility: "AI-based assessment, Multi-parameter evaluation, Technology integration required",
    //     features: [
    //         "AI-powered Risk Assessment",
    //         "Automated Partner Matching",
    //         "Real-time Analytics",
    //         "Technology Integration",
    //         "Optimal Risk Distribution"
    //     ],
    //     contactEmail: "tech@synergy-lending.com",
    //     contactPhone: "+91-9876543220",
    //     established: "2019",
    //     totalDisbursed: "₹6,800 Crores",
    //     activeLoans: "42,000+",
    //     website: "https://synergy-lending.com"
    // },
    // {
    //     id: 12,
    //     name: "Alliance Finance Partners",
    //     category: "CO_LENDING_PARTNERSHIPS",
    //     logo: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=200&h=200&fit=crop&crop=center",
    //     description: "Specialized co-lending alliance for infrastructure and project financing with institutional partners.",
    //     shortDescription: "Specialized co-lending alliance for infrastructure and project financing.",
    //     specialties: ["Infrastructure Co-lending", "Project Finance", "Institutional Partnerships", "Long-term Financing"],
    //     loanRange: "₹10,00,000 - ₹200,00,00,000",
    //     processingTime: "21-45 days",
    //     interestRate: "7% - 18% per annum",
    //     eligibility: "Project viability, Institutional backing, Comprehensive due diligence",
    //     features: [
    //         "Infrastructure Specialization",
    //         "Institutional Partnerships",
    //         "Long-term Financing",
    //         "Project Viability Assessment",
    //         "Regulatory Compliance Support"
    //     ],
    //     contactEmail: "alliance@finance-partners.com",
    //     contactPhone: "+91-9876543221",
    //     established: "2014",
    //     totalDisbursed: "₹35,000 Crores",
    //     activeLoans: "15,000+",
    //     website: "https://alliance-finance.com"
    // }
];

export const filterOptions = [
    { key: 'ALL', label: 'All Partners' },
    { key: 'Fintech partners', label: 'Fintech partners' },
    // { key: 'Fintech partners', label: 'Fintech partners' },
    // { key: 'Fintech partners', label: 'Fintech partners' }
]; 